export const GET_DATA_REQUEST = "GET_DATA_REQUEST";
export const GET_DATA_SUCCESS = "GET_DATA_SUCCESS";
export const GET_DATA_FAILURE = "GET_DATA_FAILURE";
export const POST_PRODUCT_SUCCESS = "POST_PRODUCT_SUCCESS";
export const DELETE_PRODUCT_SUCCESS = "POST_PRODUCT_SUCCESS";
